Update MSRV to 1.70.0 (#98)
Because `tokio-macros v2.4.0` requires rustc 1.70 or newer so cqrs needs
to update the MSRV to 1.70.0.

  error: package `tokio-macros v2.4.0` cannot be built because it requires rustc 1.70
  or newer, while the currently active rustc version is 1.63.0